#端口
server:
  port: 80

#spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  mvc:
    view:
      prefix: /
      suffix: .jsp

#mybatis
mybatis:
  type-aliases-package: com.bean
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
